CREATE TABLE "delhivery_c2c_shipments" (
	"id" varchar(40) PRIMARY KEY NOT NULL,
	"order_id" varchar(100) NOT NULL,
	"channel" varchar(100),
	"facility_name" varchar(200),
	"pickup_address" jsonb,
	"customer_name" varchar(200) NOT NULL,
	"customer_address" text NOT NULL,
	"customer_phone" varchar(20) NOT NULL,
	"customer_email" varchar(100),
	"customer_pincode" varchar(10) NOT NULL,
	"service_type" varchar(20) NOT NULL,
	"payment_mode" varchar(20) NOT NULL,
	"cod_amount" integer DEFAULT 0,
	"length_cm" integer,
	"breadth_cm" integer,
	"height_cm" integer,
	"weight_g" integer,
	"chargeable_weight_g" integer,
	"estimated_cost" integer,
	"cost_breakup" jsonb,
	"awb" varchar(100),
	"label_url" text,
	"current_status" varchar(100),
	"tracking_response" jsonb,
	"raw_request" jsonb,
	"raw_response" jsonb,
	"created_at" timestamp DEFAULT NOW(),
	"updated_at" timestamp DEFAULT NOW()
);
--> statement-breakpoint
CREATE TABLE "delhivery_shipments" (
	"id" varchar(40) PRIMARY KEY NOT NULL,
	"lr_number" varchar(40),
	"order_id" varchar(100),
	"manifest_job_id" varchar(100),
	"pickup_location_name" varchar(200),
	"consignee_name" varchar(200),
	"consignee_address" text,
	"consignee_city" varchar(100),
	"consignee_state" varchar(100),
	"consignee_pincode" varchar(10),
	"consignee_phone" varchar(20),
	"billing_address" jsonb,
	"box_count" integer,
	"total_weight_g" integer,
	"dimensions" jsonb,
	"shipment_details" jsonb,
	"invoices" jsonb,
	"payment_mode" varchar(20),
	"cod_amount" integer,
	"freight_mode" varchar(20),
	"rov_insurance" boolean,
	"dropoff_location" jsonb,
	"documents_meta" jsonb,
	"doc_files" jsonb,
	"current_status" varchar(50),
	"status_updated_at" timestamp,
	"tracking_response" jsonb,
	"label_url" text,
	"pod_url" text,
	"created_at" timestamp DEFAULT NOW(),
	"updated_at" timestamp DEFAULT NOW()
);
